// Généré depuis la liste ISO fournie — indicatifs téléphoniques internationaux.
// Le Burkina Faso est placé en tête (marché principal de la plateforme).
class CountryCallingCode {
  final String code;
  final String name;
  final String phoneCode;
  const CountryCallingCode(this.code, this.name, this.phoneCode);
}

const List<CountryCallingCode> kCountryCallingCodes = [
  CountryCallingCode('BF', 'Burkina Faso', '+226'),
  CountryCallingCode('DZ', 'Algeria', '+213'),
  CountryCallingCode('AO', 'Angola', '+244'),
  CountryCallingCode('BJ', 'Benin', '+229'),
  CountryCallingCode('BW', 'Botswana', '+267'),
  CountryCallingCode('BI', 'Burundi', '+257'),
  CountryCallingCode('CM', 'Cameroon', '+237'),
  CountryCallingCode('CV', 'Cabo Verde', '+238'),
  CountryCallingCode('CF', 'Central African Republic', '+236'),
  CountryCallingCode('TD', 'Chad', '+235'),
  CountryCallingCode('KM', 'Comoros', '+269'),
  CountryCallingCode('CD', 'Democratic Republic of the Congo', '+243'),
  CountryCallingCode('CG', 'Congo', '+242'),
  CountryCallingCode('CI', 'Côte d’Ivoire', '+225'),
  CountryCallingCode('DJ', 'Djibouti', '+253'),
  CountryCallingCode('EG', 'Egypt', '+20'),
  CountryCallingCode('GQ', 'Equatorial Guinea', '+240'),
  CountryCallingCode('ER', 'Eritrea', '+291'),
  CountryCallingCode('ET', 'Ethiopia', '+251'),
  CountryCallingCode('GA', 'Gabon', '+241'),
  CountryCallingCode('GM', 'Gambia', '+220'),
  CountryCallingCode('GH', 'Ghana', '+233'),
  CountryCallingCode('GN', 'Guinea', '+224'),
  CountryCallingCode('GW', 'Guinea-Bissau', '+245'),
  CountryCallingCode('KE', 'Kenya', '+254'),
  CountryCallingCode('LS', 'Lesotho', '+266'),
  CountryCallingCode('LR', 'Liberia', '+231'),
  CountryCallingCode('LY', 'Libya', '+218'),
  CountryCallingCode('MG', 'Madagascar', '+261'),
  CountryCallingCode('MW', 'Malawi', '+265'),
  CountryCallingCode('ML', 'Mali', '+223'),
  CountryCallingCode('MR', 'Mauritania', '+222'),
  CountryCallingCode('MU', 'Mauritius', '+230'),
  CountryCallingCode('MA', 'Morocco', '+212'),
  CountryCallingCode('MZ', 'Mozambique', '+258'),
  CountryCallingCode('NA', 'Namibia', '+264'),
  CountryCallingCode('NE', 'Niger', '+227'),
  CountryCallingCode('NG', 'Nigeria', '+234'),
  CountryCallingCode('RW', 'Rwanda', '+250'),
  CountryCallingCode('ST', 'Sao Tome and Principe', '+239'),
  CountryCallingCode('SN', 'Senegal', '+221'),
  CountryCallingCode('SC', 'Seychelles', '+248'),
  CountryCallingCode('SL', 'Sierra Leone', '+232'),
  CountryCallingCode('SO', 'Somalia', '+252'),
  CountryCallingCode('ZA', 'South Africa', '+27'),
  CountryCallingCode('SS', 'South Sudan', '+211'),
  CountryCallingCode('SD', 'Sudan', '+249'),
  CountryCallingCode('TZ', 'Tanzania', '+255'),
  CountryCallingCode('TG', 'Togo', '+228'),
  CountryCallingCode('TN', 'Tunisia', '+216'),
  CountryCallingCode('UG', 'Uganda', '+256'),
  CountryCallingCode('EH', 'Western Sahara', '+212'),
  CountryCallingCode('ZM', 'Zambia', '+260'),
  CountryCallingCode('ZW', 'Zimbabwe', '+263'),
  CountryCallingCode('AG', 'Antigua and Barbuda', '+1'),
  CountryCallingCode('AR', 'Argentina', '+54'),
  CountryCallingCode('AW', 'Aruba', '+297'),
  CountryCallingCode('BS', 'Bahamas', '+1'),
  CountryCallingCode('BB', 'Barbados', '+1'),
  CountryCallingCode('BZ', 'Belize', '+501'),
  CountryCallingCode('BM', 'Bermuda', '+1'),
  CountryCallingCode('BO', 'Bolivia', '+591'),
  CountryCallingCode('BR', 'Brazil', '+55'),
  CountryCallingCode('CA', 'Canada', '+1'),
  CountryCallingCode('CL', 'Chile', '+56'),
  CountryCallingCode('CO', 'Colombia', '+57'),
  CountryCallingCode('CR', 'Costa Rica', '+506'),
  CountryCallingCode('CU', 'Cuba', '+53'),
  CountryCallingCode('DM', 'Dominica', '+1'),
  CountryCallingCode('DO', 'Dominican Republic', '+1'),
  CountryCallingCode('EC', 'Ecuador', '+593'),
  CountryCallingCode('SV', 'El Salvador', '+503'),
  CountryCallingCode('FK', 'Falkland Islands', '+500'),
  CountryCallingCode('GF', 'French Guiana', '+594'),
  CountryCallingCode('GL', 'Greenland', '+299'),
  CountryCallingCode('GD', 'Grenada', '+1'),
  CountryCallingCode('GP', 'Guadeloupe', '+590'),
  CountryCallingCode('GT', 'Guatemala', '+502'),
  CountryCallingCode('GY', 'Guyana', '+592'),
  CountryCallingCode('HT', 'Haiti', '+509'),
  CountryCallingCode('HN', 'Honduras', '+504'),
  CountryCallingCode('JM', 'Jamaica', '+1'),
  CountryCallingCode('MQ', 'Martinique', '+596'),
  CountryCallingCode('MX', 'Mexico', '+52'),
  CountryCallingCode('MS', 'Montserrat', '+1'),
  CountryCallingCode('NI', 'Nicaragua', '+505'),
  CountryCallingCode('PA', 'Panama', '+507'),
  CountryCallingCode('PY', 'Paraguay', '+595'),
  CountryCallingCode('PE', 'Peru', '+51'),
  CountryCallingCode('PR', 'Puerto Rico', '+1'),
  CountryCallingCode('BL', 'Saint Barthélemy', '+590'),
  CountryCallingCode('KN', 'Saint Kitts and Nevis', '+1'),
  CountryCallingCode('LC', 'Saint Lucia', '+1'),
  CountryCallingCode('MF', 'Saint Martin (French part)', '+590'),
  CountryCallingCode('PM', 'Saint Pierre and Miquelon', '+508'),
  CountryCallingCode('VC', 'Saint Vincent and the Grenadines', '+1'),
  CountryCallingCode('SR', 'Suriname', '+597'),
  CountryCallingCode('TT', 'Trinidad and Tobago', '+1 868'),
  CountryCallingCode('TC', 'Turks and Caicos Islands', '+1'),
  CountryCallingCode('US', 'United States of America', '+1'),
  CountryCallingCode('UY', 'Uruguay', '+598'),
  CountryCallingCode('VE', 'Venezuela', '+58'),
  CountryCallingCode('VG', 'Virgin Islands (British)', '+1'),
  CountryCallingCode('VI', 'Virgin Islands (U.S.)', '+1'),
  CountryCallingCode('AF', 'Afghanistan', '+93'),
  CountryCallingCode('AM', 'Armenia', '+374'),
  CountryCallingCode('AZ', 'Azerbaijan', '+994'),
  CountryCallingCode('BH', 'Bahrain', '+973'),
  CountryCallingCode('BD', 'Bangladesh', '+880'),
  CountryCallingCode('BT', 'Bhutan', '+975'),
  CountryCallingCode('BN', 'Brunei Darussalam', '+673'),
  CountryCallingCode('KH', 'Cambodia', '+855'),
  CountryCallingCode('CN', 'China', '+86'),
  CountryCallingCode('GE', 'Georgia', '+995'),
  CountryCallingCode('HK', 'Hong Kong', '+852'),
  CountryCallingCode('IN', 'India', '+91'),
  CountryCallingCode('ID', 'Indonesia', '+62'),
  CountryCallingCode('IR', 'Iran (Islamic Republic of)', '+98'),
  CountryCallingCode('IQ', 'Iraq', '+964'),
  CountryCallingCode('IL', 'Israel', '+972'),
  CountryCallingCode('JP', 'Japan', '+81'),
  CountryCallingCode('JO', 'Jordan', '+962'),
  CountryCallingCode('KZ', 'Kazakhstan', '+7'),
  CountryCallingCode('KW', 'Kuwait', '+965'),
  CountryCallingCode('KG', 'Kyrgyzstan', '+996'),
  CountryCallingCode('LA', 'Lao People\'s Democratic Republic', '+856'),
  CountryCallingCode('LB', 'Lebanon', '+961'),
  CountryCallingCode('MO', 'Macao', '+853'),
  CountryCallingCode('MY', 'Malaysia', '+60'),
  CountryCallingCode('MV', 'Maldives', '+960'),
  CountryCallingCode('MN', 'Mongolia', '+976'),
  CountryCallingCode('MM', 'Myanmar', '+95'),
  CountryCallingCode('NP', 'Nepal', '+977'),
  CountryCallingCode('KP', 'Democratic People\'s Republic of Korea', '+850'),
  CountryCallingCode('OM', 'Oman', '+968'),
  CountryCallingCode('PK', 'Pakistan', '+92'),
  CountryCallingCode('PS', 'State of Palestine', '+970'),
  CountryCallingCode('PH', 'Philippines', '+63'),
  CountryCallingCode('QA', 'Qatar', '+974'),
  CountryCallingCode('SA', 'Saudi Arabia', '+966'),
  CountryCallingCode('SG', 'Singapore', '+65'),
  CountryCallingCode('KR', 'Republic of Korea', '+82'),
  CountryCallingCode('LK', 'Sri Lanka', '+94'),
  CountryCallingCode('SY', 'Syrian Arab Republic', '+963'),
  CountryCallingCode('TW', 'Taiwan', '+886'),
  CountryCallingCode('TJ', 'Tajikistan', '+992'),
  CountryCallingCode('TH', 'Thailand', '+66'),
  CountryCallingCode('TL', 'Timor-Leste', '+670'),
  CountryCallingCode('TR', 'Türkiye', '+90'),
  CountryCallingCode('TM', 'Turkmenistan', '+993'),
  CountryCallingCode('AE', 'United Arab Emirates', '+971'),
  CountryCallingCode('UZ', 'Uzbekistan', '+998'),
  CountryCallingCode('VN', 'Viet Nam', '+84'),
  CountryCallingCode('YE', 'Yemen', '+967'),
  CountryCallingCode('AL', 'Albania', '+355'),
  CountryCallingCode('AD', 'Andorra', '+376'),
  CountryCallingCode('AT', 'Austria', '+43'),
  CountryCallingCode('BY', 'Belarus', '+375'),
  CountryCallingCode('BE', 'Belgium', '+32'),
  CountryCallingCode('BA', 'Bosnia and Herzegovina', '+387'),
  CountryCallingCode('BG', 'Bulgaria', '+359'),
  CountryCallingCode('HR', 'Croatia', '+385'),
  CountryCallingCode('CY', 'Cyprus', '+357'),
  CountryCallingCode('CZ', 'Czechia', '+420'),
  CountryCallingCode('DK', 'Denmark', '+45'),
  CountryCallingCode('EE', 'Estonia', '+372'),
  CountryCallingCode('FO', 'Faroe Islands', '+298'),
  CountryCallingCode('FI', 'Finland', '+358'),
  CountryCallingCode('FR', 'France', '+33'),
  CountryCallingCode('DE', 'Germany', '+49'),
  CountryCallingCode('GI', 'Gibraltar', '+350'),
  CountryCallingCode('GR', 'Greece', '+30'),
  CountryCallingCode('GG', 'Guernsey', '+44'),
  CountryCallingCode('HU', 'Hungary', '+36'),
  CountryCallingCode('IS', 'Iceland', '+354'),
  CountryCallingCode('IE', 'Ireland', '+353'),
  CountryCallingCode('IM', 'Isle of Man', '+44'),
  CountryCallingCode('IT', 'Italy', '+39'),
  CountryCallingCode('JE', 'Jersey', '+44'),
  CountryCallingCode('LV', 'Latvia', '+371'),
  CountryCallingCode('LI', 'Liechtenstein', '+423'),
  CountryCallingCode('LT', 'Lithuania', '+370'),
  CountryCallingCode('LU', 'Luxembourg', '+352'),
  CountryCallingCode('MT', 'Malta', '+356'),
  CountryCallingCode('MD', 'Republic of Moldova', '+373'),
  CountryCallingCode('MC', 'Monaco', '+377'),
  CountryCallingCode('ME', 'Montenegro', '+382'),
  CountryCallingCode('NL', 'Netherlands', '+31'),
  CountryCallingCode('MK', 'North Macedonia', '+389'),
  CountryCallingCode('NO', 'Norway', '+47'),
  CountryCallingCode('PL', 'Poland', '+48'),
  CountryCallingCode('PT', 'Portugal', '+351'),
  CountryCallingCode('RO', 'Romania', '+40'),
  CountryCallingCode('RU', 'Russian Federation', '+7'),
  CountryCallingCode('SM', 'San Marino', '+378'),
  CountryCallingCode('RS', 'Serbia', '+381'),
  CountryCallingCode('SK', 'Slovakia', '+421'),
  CountryCallingCode('SI', 'Slovenia', '+386'),
  CountryCallingCode('ES', 'Spain', '+34'),
  CountryCallingCode('SE', 'Sweden', '+46'),
  CountryCallingCode('CH', 'Switzerland', '+41'),
  CountryCallingCode('UA', 'Ukraine', '+380'),
  CountryCallingCode('GB', 'United Kingdom of Great Britain and Northern Ireland', '+44'),
  CountryCallingCode('VA', 'Holy See', '+379'),
  CountryCallingCode('XK', 'Kosovo', '+383'),
  CountryCallingCode('AS', 'American Samoa', '+1 684'),
  CountryCallingCode('AU', 'Australia', '+61'),
  CountryCallingCode('CK', 'Cook Islands', '+682'),
  CountryCallingCode('FJ', 'Fiji', '+679'),
  CountryCallingCode('PF', 'French Polynesia', '+689'),
  CountryCallingCode('GU', 'Guam', '+1 671'),
  CountryCallingCode('KI', 'Kiribati', '+686'),
  CountryCallingCode('MH', 'Marshall Islands', '+692'),
  CountryCallingCode('FM', 'Micronesia (Federated States of)', '+691'),
  CountryCallingCode('NR', 'Nauru', '+674'),
  CountryCallingCode('NC', 'New Caledonia', '+687'),
  CountryCallingCode('NZ', 'New Zealand', '+64'),
  CountryCallingCode('NU', 'Niue', '+683'),
  CountryCallingCode('NF', 'Norfolk Island', '+672'),
  CountryCallingCode('MP', 'Northern Mariana Islands', '+1 670'),
  CountryCallingCode('PW', 'Palau', '+680'),
  CountryCallingCode('PG', 'Papua New Guinea', '+675'),
  CountryCallingCode('PN', 'Pitcairn', '+870'),
  CountryCallingCode('WS', 'Samoa', '+685'),
  CountryCallingCode('SB', 'Solomon Islands', '+677'),
  CountryCallingCode('TK', 'Tokelau', '+690'),
  CountryCallingCode('TO', 'Tonga', '+676'),
  CountryCallingCode('TV', 'Tuvalu', '+688'),
  CountryCallingCode('VU', 'Vanuatu', '+678'),
  CountryCallingCode('WF', 'Wallis and Futuna', '+681'),
];
